M48
; DRILL file {KiCad 8.0.5} date 2025-02-04T15:21:29-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-04T15:21:29-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X5.4769Y-6.3898
T2
X5.3351Y-5.8035
X5.3351Y-6.5122
M30
